class GlobalConstants:
    TILE_SIZE = 50
    NUM_OF_ACTIONS = 4
    FONT_SIZE = 8

    PLAYER_SPEED = 60
    LEFT_ACTION = 0
    RIGHT_ACTION = 1
    UP_ACTION = 2
    DOWN_ACTION = 3

    LAND_TILE = -1
    PLANT_TILE = 0
    KEY_TILE = 1
    MINUS_TILE = 2

    MOVE_REWARD = -0.1
    KEY_REWARD = 100
    MINUS_REWARD = -100
