

class GlobalConstants:
    LAND_TILE = -1
    TABLE_TILE = 0
    EXIT_TILE = 1
    ROBOT_TYPE_MILK = 2
    ROBOT_TYPE_FIX = 3
    MILK_CAN_TILE = 4
    ERROR_TILE = 5

    SCREEN_SIZE = 300
    TILE_SIZE = 60

    NUM_OF_ACTIONS = 5

    LEFT_ACTION = 0
    RIGHT_ACTION = 1
    UP_ACTION = 2
    DOWN_ACTION = 3
    FIRE_ACTION = 4

    P1_LEFT_ACTION = 0
    P1_RIGHT_ACTION = 1
    P1_UP_ACTION = 2
    P1_DOWN_ACTION = 3
    P1_FIRE_ACTION = 4

    P2_LEFT_ACTION = 0
    P2_RIGHT_ACTION = 1
    P2_UP_ACTION = 2
    P2_DOWN_ACTION = 3
    P2_FIRE_ACTION = 4

    P3_LEFT_ACTION = 0
    P3_RIGHT_ACTION = 1
    P3_UP_ACTION = 2
    P3_DOWN_ACTION = 3
    P3_FIRE_ACTION = 4

    PLAYER_SPEED = 10
    MILK_SPEED = 20

    FONT_SIZE = 10